### ISSUE TITLE
Discord Development Won't Start 

### ISSUE THREAD

**Issue by Bear39** [CorellanStoma/Discord-Kernel-Windows-Guide#1]
Discord Development Won't Start, Update keep failing

**Comment by CorellanStoma** [comment]
hmm I had that once with someone else. Try to rename the Update.exe file for example to UpdatesX.exe start discord dev again and should it start normally quit discord at the end again and rename it to Updates.exe again.

![image](https://user-images.githubusercontent.com/58918358/179646145-c0beee6c-a1fe-4948-9589-26e18777ce51.png)

**Comment by Bear39** [comment]
Ok it's working now.. after the update I need to sign in to discord and click install update first before renaming back to Update.exe

Thank You.
